FROM debian

# Citadel dependencies
RUN apt-get update && apt-get install -y iproute2 git fswatch jq python3-qrcode python3-pip python3-yaml python3-jsonschema python3-dacite

# Dependencies used in scripts
RUN apt-get update && apt-get install -y screen

# Docker dependencies
RUN apt-get update && apt-get install -y curl rsync wget

RUN curl -fsSL https://get.docker.com | sh

COPY core ./core
COPY dev/start ./start

EXPOSE 3000

ENV OVERWRITE_NETWORK testnet 

CMD ["./start"]
